name: Publish JAR to GitHub Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Build the project and package the JAR
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: :build

      # Upload the JAR to GitHub releases
      - name: Create Release and Upload JAR
        id: upload-release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/time-limiter*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Notify if the release was successfully created
      - name: Release Created
        if: steps.upload-release.outputs.html_url != ''
        run:
          - echo "Release created at: ${{ steps.upload-release.outputs.html_url }}"
